name: 'do-oe-build'
description: 'Build openembedded project'
inputs:
  working-directory:
    description: 'Working directory for build'
    default: ./
  image:
    description: 'Name of image to build'
    required: true
  build:
    description: 'Path to build directory'
    required: true
  script:
    description: 'Path to setup script'
    required: true
  sdk:
    description: 'Whether to build SDK'
    default: 'no'
  regular:
    description: 'Whether to build image'
    default: 'yes'
  spdx:
    description: 'Export all spdx files found for regular/sdk'
    default: 'yes'
outputs:
  image_artifacts:
    description: 'Built image artifacts'
    value: ${{ steps.export.outputs.image_artifacts }}
  sdk_artifacts:
    description: ' Build sdk artifacts'
    value: ${{ steps.export.outputs.sdk_artifacts }}
  
runs:
  using: 'composite'
  steps:
    - name: 'validate env'
      shell: bash
      run: |
         [ "x${{ env.MACHINE }}" != "x" ] || exit 1
    - name: 'clean'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        rm -rf "${{ inputs.build }}"
    - name: build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        source "${{ inputs.script }}"
        if [ "${{ inputs.regular }}" = 'yes' ]; then
           bitbake "${{ inputs.image }}"
        fi
        if [ "${{ inputs.sdk }}" = 'yes' ]; then
          bitbake "${{ inputs.image }}" -c populate_sdk
        fi
    - name: export
      working-directory: ${{ inputs.working-directory }}
      id: export
      shell: bash
      run: |
        image_artifacts=""
        if [ "${{ inputs.regular }}" = 'yes' ]; then
           for f in ${{ inputs.build }}/tmp*/deploy/images/${{ env.MACHINE }}/${{ inputs.image }}-${{ env.MACHINE }}.rootfs-*; do
             image_artifacts="$image_artifacts $(realpath $f)"
           done
           # Error if no artifacts found
           [ "x$image_artifacts" != "x" ] || exit 1
           if [ "${{ inputs.spdx }}" = 'yes' ]; then
              # Add all spdx files to image_artifacts, unless already added
              for f in ${{ inputs.build }}/tmp*/deploy/images/${{ env.MACHINE }}/*.spdx.*; do
                path="$(realpath $f)"
                found="no"
                for x in $image_artifacts; do
                   if [ "$x" = "$path" ]; then
                      found="yes"
                   fi
                done
                if [ "$found" != "yes" ]; then
                   image_artifacts="$image_artifacts $path"
                fi
              done
           fi
        fi
        echo "$image_artifacts"
        echo "image_artifacts=$image_artifacts" >> $GITHUB_OUTPUT

        sdk_artifacts=""
        if [ "${{ inputs.sdk }}" = 'yes' ]; then
          for f in ${{ inputs.build }}/tmp*/deploy/sdk/oecore-*; do
            sdk_artifacts="$sdk_artifacts $(realpath $f)"
          done
          # Error if no artifacts found
          [ "x$sdk_artifacts" != "x" ] || exit 1
           if [ "${{ inputs.spdx }}" = 'yes' ]; then
              # Add all spdx files to sdk_artifacts, unless already added
              for f in ${{ inputs.build }}/tmp*/deploy/sdk/*.spdx.*; do
                path="$(realpath $f)"
                found="no"
                for x in $sdk_artifacts; do
                   if [ "$x" = "$path" ]; then
                      found="yes"
                   fi
                done
                if [ "$found" != "yes" ]; then
                   sdk_artifacts="$sdk_artifacts $path"
                fi
              done
           fi
        fi
        echo "$sdk_artifacts"
        echo "sdk_artifacts=$sdk_artifacts" >> $GITHUB_OUTPUT
